### ISSUE TITLE
Peer-to-peer code review: Sam, Recillah, Aziz and Hussen

### ISSUE THREAD

**Issue by samlorlah** [binhussen/todo-list#7]
<img src="https://media1.giphy.com/media/fvT39aAmEvCJi3Bgsf/giphy.gif"/>

**Good Job !!!**

Your project is great.
✔️ Good UI
✔️ Responsive
✔️ Clean / Organized code

**However , you might need to work on the issue(s) below:**

- The index for your task should follow the project requirement - **By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).**

**Comment by binhussen** [comment]
Thank you @Rn486, @AzizRAA and @samlorlah for your feedback, I have updated the changes as requested and made the fixes we discussed [Link here](https://github.com/binhussen/todo-list/)
